### ISSUE TITLE
Shows

### ISSUE THREAD

**Issue by JuliaSivartsson** [henceee/1dv450-hg222dv#2]
Hittade ett fel i shows#index, raden `unless @shows.nil?` exekveras eftersom **@shows** inte sätts i metoden, utan **shows** är variablen som används, så ta helt enkelt bort @-tecknet så fungerar det. Dock får jag även felmeddelande på raderna under:

```
    shows = shows.drop(@offset)
    shows = shows.take(@limit)
```

no implicit conversion from nil to integer

Jag hittar faktiskt inte varför, då jag har ungefär samma lösning i min applikation och där fungerar det ...
- **Visa alla**

Att visa alla shows fungerar bra. Förutom att de inte är sorterade så att nyaste visas överst.
Samt att det hade varit "snällare" att direkt visa vilken venue en show är på, istället för att bara skriva ut vilket venue_id och att användaren själv får kolla upp vad det är för ställe.
Jag testade lite och med din kod fungerar det här:

```
@response = {shows: shows}
respond_with @response, include: [:venue], status: :ok
```

Då visas vilken venue det är som gäller.

Alltså istället för nuvarande kod:

```
respond_with status: 200, shows: shows, selfURL: api_shows_path
```
- **Visa en**
  Fungerar bra.
- **Skapa ny show utan artist**
  Att skapa en show fungerar, men jag kan inte kolla på den efter att jag har skapat den då det inte står något i curl-filen om vilka parametrar som måste skickas med, och venue_id verkar obligatoriskt för att kunna visa en show. Den parametern står inte med i curl filen. Jag försökte lägga till "venue_id": "1" i mitt curl-anrop men den blev ändå bara null, vet inte riktigt varför men det är något som borde åtgärdas.
- **Skapa ny show med artist**
  Att skapa en show med artist fungerar, OM artisten inte finns sedan innan, det går ju inte läsa ut någon preview i curl av sidan så jag gjorde anropet i Postman istället och fick fram följande fel: "undefined method `Artist' for #Show:0x007f1d28a5d290 Did you mean? artists", på så sätt såg jag att det ligger ett litet fel i shows#create:

Raden:

```
@show.Artist << Artist.find_by_name(artist["name"])
```

Ska vara:

```
@show.artists << Artist.find_by_name(artist["name"])
```

Då fungerar det! :)
- **Uppdatera show**

Vid uppdatering av en show så får jag felet: 
undefined method `creator?' for #Api::ShowsController:0x007f1d28d08df0 Did you mean? create
På raden:

```
if creator? && current_creator == @show.creator_id
```

Vilket egentligen inte är så konstigt, vad är **creator?** Det är det första som står i metoden men jag förstår inte vad den är för något eller vart den är satt. Samma gäller **current_creator** och **@show** antar jag. 
Dessutom har jag ingen info om hur jag Autentiserar mig, jag ser att Knock är installerat men har ingen aning om hur jag ska komma åt den och logga in där.

Tar jag bort if-satsen så fungerar det så det är bara att Autentisering måste fixas till och ändra om i metoden hur man kollar att det är rätt användare som försöker uppdatera.
- **Borttagning av show**

Samma gäller för borttagning av en show som för uppdatering

---

Jag hittar i koden att man ska kunna få ut shows i närheten av en viss venue baserat på vilken adress som skrivs i url:en, men jag lyckas inte få ut något när jag testar detta. Vet inte om jag skriver fel på något sätt. Lite hjälp i api-dokumentationen hade varit trevligt.
Samma sak när det gäller att skriva in longitude och latitude i url:en, svårt för någon som inte har tillgång till koden att veta att de här funktionerna finns samt hur de ska utföras.

Jag hittar dock ingenting i koden eller någon annanstans om ifall man kan skriva in en sökfråga, tänker på kravet:
- **Med hjälp av HTTP-anrop till API:et ska man kunna skriva en sökfråga som söker händelse på lämpligt sätt.**

T.ex. att man skulle kunna söka på alla konserter som har ordet 'fest' i sig eller något.

Skulle kunna göras på följande sätt:

```
if params[:query].present?

shows = Show.where("lower(name) like :search", search: "%#{query_params.downcase}%")
end
```

URL:
test-peer-review-juliasivartsson.c9users.io/api/shows.xml?**query=fest**&key=486196f6dbe2b99a37c3eb4d1a6a7ac2

**Comment by henceee** [comment]
FIXES #2:
- Added functionality to add key in url
- before_filter :offset_limit_params, only: [:index] in shows controller, so @limit and @offset was always null, therefore rails tried a null=> integer conversion. Such a dumb mistake.

*Fixed ln 82 to @show.artists << Artist.find_by_name(artist["name"]), another stupid mistake. Don't know how that happened, that functionality was not last minute. Insufficient testing.

*To view a show, show id must be supplied, and to view artist, artist id must be supplied.Like shows/1? and artists/1. Show and artist are rendered upon creation. Unfortunately,  I did not figure out a way to dynamically show each the url for artists for each artist in the artists collection. Added url for show upon creation.
Changed ln 90 to:             render json: @show, include: [:artists], status: :ok 
So that artist is rendered in full, including id

*When testing update and delete, no errors occured for me. Strange.. Creator is defined in the base controller api_controller:

*Fixed func. for lat long params and adress and query

**Comment by henceee** [comment]
FIXES #2 (continued):
*Fixed func. for lat long params
